FROM apache/spark:3.5.0-scala2.12-java11-python3-ubuntu

USER root

# ===== System tools =====
RUN apt-get update && \
    apt-get install -y wget curl && \
    rm -rf /var/lib/apt/lists/*

# ===== Python packages =====
RUN pip3 install --no-cache-dir \
    influxdb-client==1.38.0 \
    requests==2.31.0

# ===== Apache Maven mirror =====
ARG MAVEN_BASE=https://repo.maven.apache.org/maven2

# ===== Spark connectors =====
RUN cd /opt/spark/jars && \
    wget ${MAVEN_BASE}/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar && \
    wget ${MAVEN_BASE}/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar && \
    wget ${MAVEN_BASE}/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar && \
    wget ${MAVEN_BASE}/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar && \
    wget ${MAVEN_BASE}/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    wget ${MAVEN_BASE}/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# ===== Disable Ivy =====
RUN mkdir -p /opt/spark/conf && \
    echo "spark.jars.ivy=/tmp/ivy-disabled" >> /opt/spark/conf/spark-defaults.conf && \
    echo "spark.sql.catalogImplementation=in-memory" >> /opt/spark/conf/spark-defaults.conf

# ===== Directories =====
RUN mkdir -p /opt/jobs /opt/spark-data/checkpoints && \
    chmod -R 777 /opt/spark-data /opt/jobs

USER spark
WORKDIR /opt/spark