
apiVersion: v1
kind: Service
metadata:
    name: zookeeper-service
spec:
    selector:
        app: zookeeper
    ports:
        - protocol: TCP
          port: 2181
          targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: zookeeper-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zookeeper
    template:
        metadata:
            labels:
                app: zookeeper
        spec:
            containers:
                - name: zookeeper
                  image: confluentinc/cp-zookeeper:7.0.1
                  ports:
                      - containerPort: 2181
                  env:
                      - name: ZOOKEEPER_CLIENT_PORT
                        value: '2181'
                      - name: ZOOKEEPER_TICK_TIME
                        value: '2000'

apiVersion: v1
kind: Service
metadata:
    name: kafka-service
spec:
    selector:
        app: kafka
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
                - name: kafka
                  image: confluentinc/cp-kafka:7.0.1
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_BROKER_ID
                        value: '1'
                      - name: KAFKA_ZOOKEEPER_CONNECT
                        value: 'zookeeper-service:2181'
                      - name: KAFKA_ADVERTISED_LISTENERS
                        value: PLAINTEXT://kafka-service:9092
                      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                        value: '1'

apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka-producer-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-producer
    template:
        metadata:
            labels:
                app: kafka-producer
            annotations:
                timestamp: '2025-10-29T10:55:00Z' # nên đổi thành thời gian hiện tại
        spec:
            initContainers:
                - name: init-kafka-topic
                  image: confluentinc/cp-kafka:7.0.1
                  command:
                      - 'bash'
                      - '-c'
                      - |
                          echo "Đang chờ Kafka sẵn sàng..."
                          until /usr/bin/kafka-topics --bootstrap-server kafka-service:9092 --list; do
                            sleep 2
                          done
                          echo "Kafka đã sẵn sàng. Đang tạo topic 'river_sensors'..."
                          /usr/bin/kafka-topics --bootstrap-server kafka-service:9092 --create --if-not-exists --topic river_sensors --partitions 1 --replication-factor 1
                          echo "Tạo topic thành công."
            containers:
                - name: producer-container
                  image: kafka-producer-app
                  imagePullPolicy: Never
