# Kustomization file để triển khai tất cả resources cùng lúc
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: river-analysis

resources:
  - namespace.yaml
  - storage-class.yaml
  - kafka-controller.yaml
  - kafka-broker.yaml
  - minio.yaml
  - mongodb.yaml
  - configmaps.yaml
  - persistent-volumes.yaml
  - spark-master-minio.yaml
  - spark-worker-minio.yaml
  - spark-master-mongodb.yaml
  - spark-worker-mongodb.yaml

