apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-minio
  namespace: river-analysis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-mongodb
  namespace: river-analysis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-ssd
  resources:
    requests:
      storage: 10Gi

