{
 "title": "Water Quality Dashboard",
 "tags": [
  "water",
  "quality",
  "influxdb"
 ],
 "time": { "from": "now-20y", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ammonia Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"river-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ammonia\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CCME Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"river-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ccme_score\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dissolved Oxygen Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "targets": [
    {
     "query": "from(bucket: \"river-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"dissolved_oxygen\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Quality Label Distribution (%)",
   "type": "piechart",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"river-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"quality_label\"] == \"Good\" or\n    r[\"quality_label\"] == \"Fair\" or\n    r[\"quality_label\"] == \"Marginal\" or\n    r[\"quality_label\"] == \"Poor\"\n  )\n  |> group(columns: [\"quality_label\"])\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Hardness Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mg/L as CaCO3" } },
   "targets": [
    {
     "query": "from(bucket: \"river-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hardness\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}